CREATE DATABASE IF NOT EXISTS authservice   CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS userservice   CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS expenseservice CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
